config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/users/admin' => 'users#admin'
  get '/users/new' => 'users#new'
  post '/users/admin' => 'users#create'
  # put '/users/:id' => 'users#update'
  delete '/users/:user_id&:role_id' => 'users#destroy'

  root to: "home#index"

  # get '/' => 'home#index'
  
  get '/emps' => 'employees#index'
  get '/emps/new' => 'employees#new'
  #post '/emps/new' => 'employees#create'
  post '/emps' => 'employees#create'
  get '/emps/:id' => 'employees#show'
  delete '/emps/:id' => 'employees#destroy'
  get '/emps/:id/edit' => 'employees#edit'
  put '/emps/:id' => 'employees#update'

  

  get '/payroll_sheet' => 'payroll_sheet#index'
  get '/payroll_employee' => 'payroll_employee#index'
  get '/total_sheet' => 'total_sheet#index'

  get '/dic_job_title' => 'dic_job_title#index'
  post '/dic_job_title' => 'dic_job_title#create'
  delete '/dic_job_title/:id' => 'dic_job_title#destroy'
  
  get '/dic_pay_params' => 'dic_pay_params#index'
  get '/dic_sick_rate' => 'dic_sick_rate#index'

  get '/emp_jobs_data' => 'emp_jobs_data#index'
  post '/emp_jobs_data' => 'emp_jobs_data#create'
  delete '/emp_jobs_data/:emp_id&:job_title_id&:job_start_date' => 'emp_jobs_data#destroy'

  get '/emp_salary_data' => 'emp_salary_data#index'
  post '/emp_salary_data' => 'emp_salary_data#create'
  delete '/emp_salary_data/:emp_id&:salary_start_date' => 'emp_salary_data#destroy'

  get '/emp_sick_data' => 'emp_sick_data#index'
  post '/emp_sick_data' => 'emp_sick_data#create'
  delete '/emp_sick_data/:emp_id&:date_start_sick' => 'emp_sick_data#destroy'

  get '/emp_piecework_data' => 'emp_piecework_data#index'
  post '/emp_piecework_data' => 'emp_piecework_data#create'
  delete '/emp_piecework_data/:emp_id&:contract_number' => 'emp_piecework_data#destroy'


  get '/emp_bonus_data' => 'emp_bonus_data#index'
  post '/emp_bonus_data' => 'emp_bonus_data#create'
  delete '/emp_bonus_data/:emp_id&:order_num' => 'emp_bonus_data#destroy'

  get '/emp_jobs_before' => 'emp_jobs_before#index'
  post '/emp_jobs_before' => 'emp_jobs_before#create'
  delete '/emp_jobs_before/:emp_id&:start_date&:end_date' => 'emp_jobs_before#destroy'


  #resources :employees

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <h1>MyCorp.Accaunted</h1>
  <nav class="nav">
    <a class="nav-link active" aria-current="page" href="#" hidden>главная</a>

    <div class="inner_left_container">

      <div class="container">
        <a class="nav-link" href=<%= "#{emps_path}/new" %>>новый сотрудник</a>
        создать нового сотрудника
      </div>
      <div class="container">
        <a class="nav-link" href=<%= emps_path %>>список сотрудников</a>
        просмотреть список сотрудников
      </div>
      
      <div class="container">
        <a class="nav-link" href=<%= "#{dic_job_title_path}" %>>справочник должностей</a>
        просмотреть список должностей, добавить новые должности
      </div>
      <div class="container">
        <a class="nav-link" href=<%= "#{dic_pay_params_path}" %>>справочник параметров для расчёта выплат</a>
        просмотреть справочник параметров для расчёта выплат,</br> добавить/изменить значения
      </div>
      <div class="container">
        <a class="nav-link" href=<%= "#{dic_sick_rate_path}" %>>справочник параметров расчёта больничных</a>
        просмотреть справочник параметров расчёта больничных,</br> добавить/изменить значения
      </div>
      <div class="container">
        <a class="nav-link" href=<%= "#{emp_jobs_data_path}" %>>назначение на должность</a>
        просмотреть и добавить назначения на должность
      </div>
      <div class="container">
        <a class="nav-link" href=<%= "#{emp_salary_data_path}" %>>назначение оклада</a>
        просмотреть и добавить назначение оклада
      </div>
    </div>

    <div class="inner_left_container">
      <div class="container">
        <a class="nav-link" href=<%= "#{emp_sick_data_path}" %>>невыходы по больничным</a>
        просмотреть и добавить больничные
      </div>
      <div class="container">
        <a class="nav-link" href=<%= "#{emp_piecework_data_path}" %>>сдельные работы</a>
        просмотреть и добавить сдельные работы
      </div>
      <div class="container">
        <a class="nav-link" href=<%= "#{emp_bonus_data_path}" %>>премии</a>
        просмотреть и добавить премии
      </div>
      <div class="container">
        <a class="nav-link" href=<%= "#{emp_jobs_before_path}" %>>стаж работы</a>
        просмотреть и добавить стаж работы
      </div>
      <div class="container">
        <a class="nav-link" href=<%= payroll_sheet_path %>>общий расчётный лист начисления зп</a>
        сформировать общий расчётный лист начисления зп
      </div>
      <div class="container">
        <a class="nav-link" href=<%= payroll_employee_path %>>расчётный лист начисления зп по сотруднику</a>
        сформировать расчётный лист начисления зп по сотруднику
      </div>
      <div class="container">
        <a class="nav-link" href=<%= total_sheet_path %>>итоговая ведомость выплат</a>
        сформировать итоговую ведомость выплат
      </div>
    </div>
  </nav>
</div>